### ISSUE TITLE
Code installation appears to be corrupt. Please reinstall.

### ISSUE THREAD

**Issue by Slash137** [dsoloha/native-macos#26]
Hello, recently I installed your theme, which is beautiful. 
I installed the theme, set it to **LTLE** and then installed both extensions: **Activitus Bar** and **Vibrancy**.
I set the Settings parameters as you told in your README.MD

But after the first Restart a message appears saying "_Your Code installation appears to be corrupt. Please reinstall_".
In the window title also appears the tag **[Unsupported]**.

I really wanted to use your theme and in the first instance it appears to work correctly, but after maximizing the window the sidebar became dark. It appears only when maximized.

I'm gonna use it for some days and will update if I find anything else.

PS: it would be amazing if you can add dynamic theme support.

### **Versions**
_OS_: macOS Big Sur (11.2.2) [Darwin x64 20.3.0]
_vsCode_: 1.54.1 
_Electron_: 11.3.0
_Chrome_: 87.0.4280.141
_Node.js_: 12.18.3

**Comment by Slash137** [comment]
Also if I double-click on the window bar to expand and fill all the space available in the screen, the window corners get flat instead of rounded so I have to restart the app to get the rounded corners again.

**Comment by dsoloha** [comment]
Do these issues persist when disabling the other extensions? I think Vibrancy in particular has had some issues with the most recent updates, so it could be one of those.

**Comment by dsoloha** [comment]
Also not sure what you mean by dynamic theme support.

**Comment by Slash137** [comment]
Everything was related to Vibrancy and VSCode. Your theme works perfectly.
